pipeline {
    agent any 
    
    
    stages {
        
        stage('Static Analysis') {
            steps {
                echo 'Today is my pracs' 
            }
        }
        
        stage('Pracs') {
            steps {
                echo 'Done' 
            }
        }
        
        
        stage('Compile') {
            steps {
                echo 'Code is completed' 
            }
        }
        stage('Security Check') {
            steps {
                echo 'Run the security check against the application' 
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo 'Manchester City!!!!' 
            }
        }
        stage('Run Integration Tests') {
            steps {
                echo 'Run only crucial integration tests from the source code' 
            }
        }
        stage('Publish Artifacts') {
            steps {
                echo 'No error' 
            }
        }
    }
}
